graph LR;

subgraph Grupo de las X:
  nodo_x_01["Nodo X.01"];
  nodo_x_02["Nodo X.02"];
  nodo_x_03["Nodo X.03"];
  nodo_x_04["Nodo X.04"];
  nodo_x_05["Nodo X.05"];
  nodo_x_06["Nodo X.06"];
  nodo_x_07["Nodo X.07"];
  nodo_x_08["Nodo X.08"];
  nodo_x_09["Nodo X.09"];
  nodo_x_010["Nodo X.010"];
  nodo_x_011["Nodo X.011"];
  nodo_x_012["Nodo X.012"];
  nodo_x_013["Nodo X.013"];
  nodo_x_014["Nodo X.014"];
  nodo_x_015["Nodo X.015"];
  nodo_x_016["Nodo X.016"];
  nodo_x_017["Nodo X.017"];
  nodo_x_018["Nodo X.018"];
  nodo_x_019["Nodo X.019"];
end
subgraph Grupo de las Y:
  nodo_y_01["Nodo Y.01"];
  nodo_y_02["Nodo Y.02"];
  nodo_y_03["Nodo Y.03"];
  nodo_y_04["Nodo Y.04"];
  nodo_y_05["Nodo Y.05"];
  nodo_y_06["Nodo Y.06"];
  nodo_y_07["Nodo Y.07"];
  nodo_y_08["Nodo Y.08"];
  nodo_y_09["Nodo Y.09"];
  nodo_y_010["Nodo Y.010"];
  nodo_y_011["Nodo Y.011"];
  nodo_y_012["Nodo Y.012"];
  nodo_y_013["Nodo Y.013"];
  nodo_y_014["Nodo Y.014"];
  nodo_y_015["Nodo Y.015"];
  nodo_y_016["Nodo Y.016"];
  nodo_y_017["Nodo Y.017"];
  nodo_y_018["Nodo Y.018"];
  nodo_y_019["Nodo Y.019"];
end
subgraph Grupo de las Z:
  nodo_z_01["Nodo Z.01"];
  nodo_z_02["Nodo Z.02"];
  nodo_z_03["Nodo Z.03"];
  nodo_z_04["Nodo Z.04"];
  nodo_z_05["Nodo Z.05"];
  nodo_z_06["Nodo Z.06"];
  nodo_z_07["Nodo Z.07"];
  nodo_z_08["Nodo Z.08"];
  nodo_z_09["Nodo Z.09"];
  nodo_z_010["Nodo Z.010"];
  nodo_z_011["Nodo Z.011"];
  nodo_z_012["Nodo Z.012"];
  nodo_z_013["Nodo Z.013"];
  nodo_z_014["Nodo Z.014"];
  nodo_z_015["Nodo Z.015"];
  nodo_z_016["Nodo Z.016"];
  nodo_z_017["Nodo Z.017"];
  nodo_z_018["Nodo Z.018"];
  nodo_z_019["Nodo Z.019"];
end
subgraph Grupo de las W:
  nodo_w_01["Nodo W.01"];
  nodo_w_02["Nodo W.02"];
  nodo_w_03["Nodo W.03"];
  nodo_w_04["Nodo W.04"];
  nodo_w_05["Nodo W.05"];
  nodo_w_06["Nodo W.06"];
  nodo_w_07["Nodo W.07"];
  nodo_w_08["Nodo W.08"];
  nodo_w_09["Nodo W.09"];
  nodo_w_010["Nodo W.010"];
  nodo_w_011["Nodo W.011"];
  nodo_w_012["Nodo W.012"];
  nodo_w_013["Nodo W.013"];
  nodo_w_014["Nodo W.014"];
  nodo_w_015["Nodo W.015"];
  nodo_w_016["Nodo W.016"];
  nodo_w_017["Nodo W.017"];
  nodo_w_018["Nodo W.018"];
  nodo_w_019["Nodo W.019"];
end

nodo_x_01 -- relación estrecha --> nodo_w_01
nodo_x_02 -- relación estrecha --> nodo_w_02
nodo_x_03 -- relación estrecha --> nodo_w_03
nodo_x_04 -- relación estrecha --> nodo_w_04
nodo_x_05 -- relación estrecha --> nodo_w_05
nodo_x_06 -- relación estrecha --> nodo_w_06
nodo_x_07 -- relación estrecha --> nodo_w_07
nodo_x_08 -- relación estrecha --> nodo_w_08
nodo_x_09 -- relación estrecha --> nodo_w_09
nodo_x_01 -- relación estrecha --> nodo_y_01
nodo_x_02 -- relación estrecha --> nodo_y_02
nodo_x_03 -- relación estrecha --> nodo_y_03
nodo_x_04 -- relación estrecha --> nodo_y_04
nodo_x_05 -- relación estrecha --> nodo_y_05
nodo_x_06 -- relación estrecha --> nodo_y_06
nodo_x_07 -- relación estrecha --> nodo_y_07
nodo_x_08 -- relación estrecha --> nodo_y_08
nodo_x_09 -- relación estrecha --> nodo_y_09
nodo_x_01 -- relación estrecha --> nodo_z_01
nodo_x_02 -- relación estrecha --> nodo_z_02
nodo_x_03 -- relación estrecha --> nodo_z_03
nodo_x_04 -- relación estrecha --> nodo_z_04
nodo_x_05 -- relación estrecha --> nodo_z_05
nodo_x_06 -- relación estrecha --> nodo_z_06
nodo_x_07 -- relación estrecha --> nodo_z_07
nodo_x_08 -- relación estrecha --> nodo_z_08
nodo_x_09 -- relación estrecha --> nodo_z_09

